#### Bays Theorm 

$$ P(A|B) = \frac {P(A).P(B|A)} {P(B)} $$

$$ P(A|B) \propto P(B|A).P(A) $$

$$ \text{Posterior Probality} \propto \text{Likelihood . Prior Probability} $$

here $ P(A|B) = \text {Posterior Probability} $ and $ P(A) =\text{ Piror Probability} $ and $ P(B|A) --> Likelihood $ and $P(B) = \text {Normalizing Constant} $

    x = features
    y = target ( categorical )

    MultinomialNB --> Text Classification ( setosa,versicolor,virginica) 
    Bernoulli Naive Bayes --> 2 - target  (spam , not spam)
    GaussionNB --> target --> Quantative(continous) ## price --> feature


In [1]:
import numpy as np 
import matplotlib.pyplot as plt
import seaborn as sns 
import pandas as pd
%matplotlib inline
plt.rcParams['figure.figsize'] = (10,4)

In [2]:
from sklearn import datasets

In [3]:
iris = datasets.load_iris()

In [4]:
type(iris)

sklearn.utils.Bunch

In [5]:
dir(iris)

['DESCR', 'data', 'feature_names', 'filename', 'target', 'target_names']

In [6]:
print(iris['DESCR'])

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [8]:
iris['data'][:5]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [10]:
print(iris.feature_names)

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [11]:
iris['target'][:5]

array([0, 0, 0, 0, 0])

In [12]:
iris['target_names']

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [13]:
features = pd.DataFrame(iris['data'],columns=iris['feature_names'])

In [14]:
features.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [16]:
iris['target_names']

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [17]:
target = pd.Series(iris['target']).map({0:'Setosa',1:'Versicolor',
                                       2:'Virginica'})
target.head()

0    Setosa
1    Setosa
2    Setosa
3    Setosa
4    Setosa
dtype: object

In [18]:
from sklearn.model_selection import train_test_split

In [19]:
X_train,X_test,y_train,y_test = train_test_split(features,target,
                            test_size=0.30)

### MultinomialNB

In [20]:
from sklearn.naive_bayes import MultinomialNB

In [21]:
model = MultinomialNB()

In [22]:
model.fit(X_train,y_train)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [23]:
y_pred = model.predict(X_test)

In [25]:
X_test[:5]

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
115                6.4               3.2                5.3               2.3
53                 5.5               2.3                4.0               1.3
79                 5.7               2.6                3.5               1.0
62                 6.0               2.2                4.0               1.0
47                 4.6               3.2                1.4               0.2

In [24]:
y_pred[:5]

array(['Virginica', 'Versicolor', 'Versicolor', 'Versicolor', 'Setosa'],
      dtype='<U10')

In [28]:
np.array(y_test[:5])

array(['Virginica', 'Versicolor', 'Versicolor', 'Versicolor', 'Setosa'],
      dtype=object)

### Evaluation 

In [29]:
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score

In [30]:
print(confusion_matrix(y_test,y_pred))

[[14  0  0]
 [ 0 15  1]
 [ 0  0 15]]


In [31]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

      Setosa       1.00      1.00      1.00        14
  Versicolor       1.00      0.94      0.97        16
   Virginica       0.94      1.00      0.97        15

   micro avg       0.98      0.98      0.98        45
   macro avg       0.98      0.98      0.98        45
weighted avg       0.98      0.98      0.98        45



In [32]:
accuracy_score(y_test,y_pred)

0.9777777777777777

#### Image Classification 